routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/search', 'SearchController@index')->name('search');
Route::get('/search/results', 'SearchController@list')->name('search.results');
Route::get('/view/theses/{slug}', 'SearchController@view')->name('search.view.theses');

Auth::routes();


//Route::get('/user/profile', 'DashboardController@profile')->name('user.profile');
//Route::resource('profile', 'ProfileController');

Route::middleware(['auth'])->group(function () {
    Route::get('/profile/edit', 'ProfileController@edit')->name('user.profile.edit');
    Route::put('/profile/update', 'ProfileController@update')->name('user.profile.update');
});

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('permissions','PermissionController');
    Route::resource('domains','DomainController');

    Route::get('notifications/domains','NotificationController@domains')->name('show.domain.notifications');
    Route::get('notifications/domains/{id}/modal','NotificationController@domains_show')->name('show.domain.notifications.modal');
    Route::post('notifications/{id}/verify','AjaxController@notification_verify')->name('ajax.notifications.verify');
    Route::post('notifications/{id}/update','AjaxController@notification_update')->name('ajax.notifications.update');
});

Route::middleware(['auth', 'profile'])->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/profile/avatar', 'ProfileController@avatar')->name('user.profile.avatar');
    Route::post('/profile/avatar/update', 'ProfileController@avatar_update')->name('user.profile.avatar.update');
    Route::get('/profile/password', 'ProfileController@change_password')->name('user.profile.change.password');
    Route::put('/profile/password/update', 'ProfileController@update_password')->name('user.profile.update.password');

    Route::resource('theses','ThesesController');
    Route::get('theses/{slug}', 'ThesesController@show')->name('theses.slug');
    Route::get('theses/download/{id}', 'ThesesController@download')->name('theses.download');
});

app/Domain.php
<?php

namespace App;

use App\Events\DomainCreated;
use App\Mail\DomainCreationAlert;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use ScoutElastic\Searchable;


class Domain extends Model implements AuditableContract
{

    use Notifiable, Auditable, Searchable;

    const UNDER_REVIEW = 2;
    const APPROVED = 1;
    const UNAPPROVED = 0;
    /**
     * @var array
     */
    public static $approval = [
        self::UNAPPROVED => "Unapproved",
        self::APPROVED => "Approved",
        self::UNDER_REVIEW => "Under review",
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'slug',
        'approved',
        'user_id'
    ];

    protected $dispatchesEvents = [
        'created' => DomainCreated::class
    ];

    protected $indexConfigurator = DomainIndexConfigurator::class;

    protected $mapping = [

        'properties' => [

            'id' => [
                'type' => 'integer'
            ],

            'name' => [
                'type' => 'keyword',
                'normalizer' => 'lowercase_normalizer'
            ],

            'approved' => [
                'type' => 'integer'
            ],


        ]
    ];

    /*protected static function boot()
    {
        parent::boot();

        static::created( function($domain) {
            if ($domain->approved == self::UNDER_REVIEW) {
                $user = Auth::user();
                Mail::to($user)->send(new DomainCreationAlert($user, $domain));
            }
        });
    }*/

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = $value;
        $this->attributes['slug'] = str_slug($value);
    }


    /**
     * Get the user that owns the phone.
     */
    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Theses.
     */
    public function theses()
    {
        return $this->hasMany(Thesis::class);
    }

    /**
     * Scope a query to only include active users.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('approved', 1);
    }

    /**
     * @param $query
     * @return array $manufacturersAsArray
     * @throws \Exception
     */
    public function scopeToOptionArray($query)
    {
        $types = $query->get(['id', 'name']);

        $typeAsArray = [];
        foreach ($types as $type) {
            $typeAsArray[$type->id] =  $type->name;
        }

        return $typeAsArray;
    }

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        $array =
            [
                'id' => $this->id,
                'name' => $this->name,
                'approved' => $this->approved,
            ];

        // Customize array...

        return $array;
    }
}

app/Http/Controllers/DomainController.php
<?php

namespace App\Http\Controllers;

use App\Domain;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DomainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:domain-list');
        $this->middleware('permission:domain-create', ['only' => ['create','store']]);
        $this->middleware('permission:domain-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:domain-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $domains = Domain::orderBy('id','DESC')->paginate(10);
        return view('domains.index',compact('domains'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('domains.create');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        $this->validate($request, [
            'name' => 'required|min:3|max:255',
            'approved' => 'required|integer|between:0,1',
        ]);

        Domain::create([
            'name' => $request->get('name'),
            'approved' => $request->get('approved'),
            'description' => $request->get('description'),
            'user_id' => $user->id
        ]);

        return redirect()->route('domains.index')
            ->with('success','Domain created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/domains/create.blade.php
@extends('layouts.main')

@section('background', 'lb')

@section('homehero')
    @include('layouts.homehero.book')
@endsection

@section('content')
    <div class="content col-md-12" style="padding-top: 50px;">
        <div class="post-padding" style="padding-top: 30px;">
            <div class="job-title nocover hidden-sm hidden-xs"><h3>Create Domain</h3></div>


            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('domains.index') }}">Back</a>
                    </div>
                </div>
            </div>


            @include('layouts.partials.errors.forms')

            {!! Form::open(['route' => 'domains.store','method'=>'POST', 'class' => 'submit-form']) !!}

            {!! Form::token(); !!}
            <div class="row">

                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                        {!! Form::label('name', 'Name:', ['class' => 'control-label']) !!}
                        {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' =>'Domain name', 'required']) !!}
                        </div>
                    </div>
                </div>

                <hr class="invis">

                <div class="row">
                    <div class="col-md-6 col-sm-12">

                        <div class="form-group">
                            {!! Form::label('approved', 'Status', ['class' => 'control-label']) !!}
                            {!! Form::select(
                                'approved',
                                App\Domain::$approval,
                                old('approved'),
                                ['class' => 'selectpicker', 'data-style' => 'btn-default', 'data-live-search' => 'false', 'placeholder' => 'Select...'])
                            !!}
                        </div>
                    </div>
                </div>

                <hr class="invis">

                <div class="row">
                    <div class="col-md-12 col-sm-12">

                        {!! Form::label('description', 'Short Description', ['class' => 'control-label']) !!}
                        {!! Form::textarea('description', old('description'), ['class' => 'form-control', 'placeholder' =>'Domain short description']) !!}

                    </div>
                </div><!-- end row -->


                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Create Domain</button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>

@endsection

resources/views/domains/edit.blade.php
@extends('layouts.main')

@section('background', 'lb')

@section('homehero')
    @include('layouts.homehero.book')
@endsection


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Role</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Permission:</strong>
                <br/>
                @foreach($permission as $value)
                    <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                        {{ $value->name }}</label>
                    <br/>
                @endforeach
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
    {!! Form::close() !!}


@endsection

resources/views/domains/index.blade.php
@extends('layouts.main')

@section('background', 'lb')

@section('homehero')
    @include('layouts.homehero.book')
@endsection


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Domains Management</h2>
            </div>
            <div class="pull-right">
                @can('role-create')
                    <a class="btn btn-success" href="{{ route('domains.create') }}"> Create New Permission</a>
                @endcan
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Slug</th>
            <th>Approved</th>
            <th width="280px">Action</th>
        </tr>

        @if(!$domains->isEmpty())
            @foreach ($domains as $key => $val)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $val->name }}</td>
                    <td>{{ $val->slug }}</td>
                    <td>{{ $val->approved }}</td>
                    <td>
                        <a class="btn btn-info" href="{{ route('domains.show',$val->id) }}">Show</a>
                        @can('role-edit')
                            <a class="btn btn-primary" href="{{ route('domains.edit',$val->id) }}">Edit</a>
                        @endcan
                        @can('role-delete')
                            {!! Form::open(['method' => 'DELETE','route' => ['permissions.destroy', $val->id],'style'=>'display:inline']) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}
                        @endcan
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="5">No data</td>
            </tr>
        @endif



    </table>


    {!! $domains->render() !!}


@endsection

resources/views/domains/show.blade.php
@extends('layouts.main')

@section('background', 'lb')

@section('homehero')
    @include('layouts.homehero.book')
@endsection


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Role</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $role->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Permissions:</strong>
                @if(!empty($rolePermissions))
                    @foreach($rolePermissions as $v)
                        <label class="label label-success">{{ $v->name }},</label>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection